<h1>Мои дети:</h1>
<table>
    <tr>
        <td>
            <b>#</b>
        </td>
        <td>
            <b>NAME</b>
        </td>
        <td>
            <b>AGE</b>
        </td>
    </tr>
    <?php foreach ($children as $child): ?>
        <tr>
            <td>
                <?= htmlspecialchars($child['id']) ?>.
            </td>
            <td>
                <?= htmlspecialchars($child['name']) ?>,
            </td>
            <td>
                <?= htmlspecialchars($child['age']) ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>